<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Appends events to an existing DataSet.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.AppendEventsRequest</code>
 */
class AppendEventsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Events to be appended.
     * Note:
     * 0. The [DataSet][google.cloud.timeseriesinsights.v1.DataSet] must be shown in a `LOADED` state
     *    in the results of `list` method; otherwise, all events from
     *    the append request will be dropped, and a `NOT_FOUND` status will be
     *    returned.
     * 0. All events in a single request must have the same
     *    [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] if set; otherwise, an
     *    `INVALID_ARGUMENT` status will be returned.
     * 0. If [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] is not set (or 0), there
     *    should be only 1 event; otherwise, an `INVALID_ARGUMENT` status will be
     *    returned.
     * 0. The events must be newer than the current time minus
     *    [DataSet TTL][google.cloud.timeseriesinsights.v1.DataSet.ttl] or they will be dropped.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.Event events = 1;</code>
     */
    private $events;
    /**
     * Required. The DataSet to which we want to append to in the format of
     * "projects/{project}/datasets/{dataset}"
     *
     * Generated from protobuf field <code>string dataset = 2 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $dataset = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Google\Cloud\Timeseriesinsights\V1\Event>|\Google\Protobuf\Internal\RepeatedField $events
     *           Events to be appended.
     *           Note:
     *           0. The [DataSet][google.cloud.timeseriesinsights.v1.DataSet] must be shown in a `LOADED` state
     *              in the results of `list` method; otherwise, all events from
     *              the append request will be dropped, and a `NOT_FOUND` status will be
     *              returned.
     *           0. All events in a single request must have the same
     *              [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] if set; otherwise, an
     *              `INVALID_ARGUMENT` status will be returned.
     *           0. If [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] is not set (or 0), there
     *              should be only 1 event; otherwise, an `INVALID_ARGUMENT` status will be
     *              returned.
     *           0. The events must be newer than the current time minus
     *              [DataSet TTL][google.cloud.timeseriesinsights.v1.DataSet.ttl] or they will be dropped.
     *     @type string $dataset
     *           Required. The DataSet to which we want to append to in the format of
     *           "projects/{project}/datasets/{dataset}"
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * Events to be appended.
     * Note:
     * 0. The [DataSet][google.cloud.timeseriesinsights.v1.DataSet] must be shown in a `LOADED` state
     *    in the results of `list` method; otherwise, all events from
     *    the append request will be dropped, and a `NOT_FOUND` status will be
     *    returned.
     * 0. All events in a single request must have the same
     *    [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] if set; otherwise, an
     *    `INVALID_ARGUMENT` status will be returned.
     * 0. If [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] is not set (or 0), there
     *    should be only 1 event; otherwise, an `INVALID_ARGUMENT` status will be
     *    returned.
     * 0. The events must be newer than the current time minus
     *    [DataSet TTL][google.cloud.timeseriesinsights.v1.DataSet.ttl] or they will be dropped.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.Event events = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Events to be appended.
     * Note:
     * 0. The [DataSet][google.cloud.timeseriesinsights.v1.DataSet] must be shown in a `LOADED` state
     *    in the results of `list` method; otherwise, all events from
     *    the append request will be dropped, and a `NOT_FOUND` status will be
     *    returned.
     * 0. All events in a single request must have the same
     *    [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] if set; otherwise, an
     *    `INVALID_ARGUMENT` status will be returned.
     * 0. If [groupId][google.cloud.timeseriesinsights.v1.Event.group_id] is not set (or 0), there
     *    should be only 1 event; otherwise, an `INVALID_ARGUMENT` status will be
     *    returned.
     * 0. The events must be newer than the current time minus
     *    [DataSet TTL][google.cloud.timeseriesinsights.v1.DataSet.ttl] or they will be dropped.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.Event events = 1;</code>
     * @param array<\Google\Cloud\Timeseriesinsights\V1\Event>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Timeseriesinsights\V1\Event::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Required. The DataSet to which we want to append to in the format of
     * "projects/{project}/datasets/{dataset}"
     *
     * Generated from protobuf field <code>string dataset = 2 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getDataset()
    {
        return $this->dataset;
    }

    /**
     * Required. The DataSet to which we want to append to in the format of
     * "projects/{project}/datasets/{dataset}"
     *
     * Generated from protobuf field <code>string dataset = 2 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setDataset($var)
    {
        GPBUtil::checkString($var, True);
        $this->dataset = $var;

        return $this;
    }

}

