<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response for an AppendEvents RPC.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.AppendEventsResponse</code>
 */
class AppendEventsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Dropped events; empty if all events are successfully added.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.Event dropped_events = 1;</code>
     */
    private $dropped_events;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Google\Cloud\Timeseriesinsights\V1\Event>|\Google\Protobuf\Internal\RepeatedField $dropped_events
     *           Dropped events; empty if all events are successfully added.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * Dropped events; empty if all events are successfully added.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.Event dropped_events = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDroppedEvents()
    {
        return $this->dropped_events;
    }

    /**
     * Dropped events; empty if all events are successfully added.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.Event dropped_events = 1;</code>
     * @param array<\Google\Cloud\Timeseriesinsights\V1\Event>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDroppedEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Timeseriesinsights\V1\Event::class);
        $this->dropped_events = $arr;

        return $this;
    }

}

