<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Mapping of BigQuery columns to timestamp, group_id and dimensions.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.BigqueryMapping</code>
 */
class BigqueryMapping extends \Google\Protobuf\Internal\Message
{
    /**
     * The column which should be used as the event timestamps. If not specified
     * 'Timestamp' is used by default. The column may have TIMESTAMP or INT64
     * type (the latter is interpreted as microseconds since the Unix epoch).
     *
     * Generated from protobuf field <code>string timestamp_column = 1;</code>
     */
    protected $timestamp_column = '';
    /**
     * The column which should be used as the group ID (grouping events into
     * sessions). If not specified 'GroupId' is used by default, if the input
     * table does not have such a column, random unique group IDs are
     * generated automatically (different group ID per input row).
     *
     * Generated from protobuf field <code>string group_id_column = 2;</code>
     */
    protected $group_id_column = '';
    /**
     * The list of columns that should be translated to dimensions. If empty,
     * all columns are translated to dimensions. The timestamp and group_id
     * columns should not be listed here again. Columns are expected to have
     * primitive types (STRING, INT64, FLOAT64 or NUMERIC).
     *
     * Generated from protobuf field <code>repeated string dimension_column = 3;</code>
     */
    private $dimension_column;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $timestamp_column
     *           The column which should be used as the event timestamps. If not specified
     *           'Timestamp' is used by default. The column may have TIMESTAMP or INT64
     *           type (the latter is interpreted as microseconds since the Unix epoch).
     *     @type string $group_id_column
     *           The column which should be used as the group ID (grouping events into
     *           sessions). If not specified 'GroupId' is used by default, if the input
     *           table does not have such a column, random unique group IDs are
     *           generated automatically (different group ID per input row).
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $dimension_column
     *           The list of columns that should be translated to dimensions. If empty,
     *           all columns are translated to dimensions. The timestamp and group_id
     *           columns should not be listed here again. Columns are expected to have
     *           primitive types (STRING, INT64, FLOAT64 or NUMERIC).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * The column which should be used as the event timestamps. If not specified
     * 'Timestamp' is used by default. The column may have TIMESTAMP or INT64
     * type (the latter is interpreted as microseconds since the Unix epoch).
     *
     * Generated from protobuf field <code>string timestamp_column = 1;</code>
     * @return string
     */
    public function getTimestampColumn()
    {
        return $this->timestamp_column;
    }

    /**
     * The column which should be used as the event timestamps. If not specified
     * 'Timestamp' is used by default. The column may have TIMESTAMP or INT64
     * type (the latter is interpreted as microseconds since the Unix epoch).
     *
     * Generated from protobuf field <code>string timestamp_column = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTimestampColumn($var)
    {
        GPBUtil::checkString($var, True);
        $this->timestamp_column = $var;

        return $this;
    }

    /**
     * The column which should be used as the group ID (grouping events into
     * sessions). If not specified 'GroupId' is used by default, if the input
     * table does not have such a column, random unique group IDs are
     * generated automatically (different group ID per input row).
     *
     * Generated from protobuf field <code>string group_id_column = 2;</code>
     * @return string
     */
    public function getGroupIdColumn()
    {
        return $this->group_id_column;
    }

    /**
     * The column which should be used as the group ID (grouping events into
     * sessions). If not specified 'GroupId' is used by default, if the input
     * table does not have such a column, random unique group IDs are
     * generated automatically (different group ID per input row).
     *
     * Generated from protobuf field <code>string group_id_column = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupIdColumn($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id_column = $var;

        return $this;
    }

    /**
     * The list of columns that should be translated to dimensions. If empty,
     * all columns are translated to dimensions. The timestamp and group_id
     * columns should not be listed here again. Columns are expected to have
     * primitive types (STRING, INT64, FLOAT64 or NUMERIC).
     *
     * Generated from protobuf field <code>repeated string dimension_column = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDimensionColumn()
    {
        return $this->dimension_column;
    }

    /**
     * The list of columns that should be translated to dimensions. If empty,
     * all columns are translated to dimensions. The timestamp and group_id
     * columns should not be listed here again. Columns are expected to have
     * primitive types (STRING, INT64, FLOAT64 or NUMERIC).
     *
     * Generated from protobuf field <code>repeated string dimension_column = 3;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDimensionColumn($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->dimension_column = $arr;

        return $this;
    }

}

