<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Create a DataSet request.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.CreateDataSetRequest</code>
 */
class CreateDataSetRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. Client project name which will own this DataSet in the format of
     * 'projects/{project}'.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $parent = '';
    /**
     * Required. Dataset to be loaded.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.DataSet dataset = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $dataset = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $parent
     *           Required. Client project name which will own this DataSet in the format of
     *           'projects/{project}'.
     *     @type \Google\Cloud\Timeseriesinsights\V1\DataSet $dataset
     *           Required. Dataset to be loaded.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. Client project name which will own this DataSet in the format of
     * 'projects/{project}'.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * Required. Client project name which will own this DataSet in the format of
     * 'projects/{project}'.
     *
     * Generated from protobuf field <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setParent($var)
    {
        GPBUtil::checkString($var, True);
        $this->parent = $var;

        return $this;
    }

    /**
     * Required. Dataset to be loaded.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.DataSet dataset = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Google\Cloud\Timeseriesinsights\V1\DataSet|null
     */
    public function getDataset()
    {
        return $this->dataset;
    }

    public function hasDataset()
    {
        return isset($this->dataset);
    }

    public function clearDataset()
    {
        unset($this->dataset);
    }

    /**
     * Required. Dataset to be loaded.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.DataSet dataset = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Google\Cloud\Timeseriesinsights\V1\DataSet $var
     * @return $this
     */
    public function setDataset($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Timeseriesinsights\V1\DataSet::class);
        $this->dataset = $var;

        return $this;
    }

}

