<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A data source consists of multiple [Event][google.cloud.timeseriesinsights.v1.Event] objects stored on
 * Cloud Storage.  Each Event should be in JSON format, with one Event
 * per line, also known as JSON Lines format.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.DataSource</code>
 */
class DataSource extends \Google\Protobuf\Internal\Message
{
    /**
     * Data source URI.
     * 1) Google Cloud Storage files (JSON) are defined in the following form.
     * `gs://bucket_name/object_name`. For more information on Cloud Storage URIs,
     * please see https://cloud.google.com/storage/docs/reference-uris.
     *
     * Generated from protobuf field <code>string uri = 1;</code>
     */
    protected $uri = '';
    /**
     * For BigQuery inputs defines the columns that should be used for dimensions
     * (including time and group ID).
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.BigqueryMapping bq_mapping = 2;</code>
     */
    protected $bq_mapping = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $uri
     *           Data source URI.
     *           1) Google Cloud Storage files (JSON) are defined in the following form.
     *           `gs://bucket_name/object_name`. For more information on Cloud Storage URIs,
     *           please see https://cloud.google.com/storage/docs/reference-uris.
     *     @type \Google\Cloud\Timeseriesinsights\V1\BigqueryMapping $bq_mapping
     *           For BigQuery inputs defines the columns that should be used for dimensions
     *           (including time and group ID).
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * Data source URI.
     * 1) Google Cloud Storage files (JSON) are defined in the following form.
     * `gs://bucket_name/object_name`. For more information on Cloud Storage URIs,
     * please see https://cloud.google.com/storage/docs/reference-uris.
     *
     * Generated from protobuf field <code>string uri = 1;</code>
     * @return string
     */
    public function getUri()
    {
        return $this->uri;
    }

    /**
     * Data source URI.
     * 1) Google Cloud Storage files (JSON) are defined in the following form.
     * `gs://bucket_name/object_name`. For more information on Cloud Storage URIs,
     * please see https://cloud.google.com/storage/docs/reference-uris.
     *
     * Generated from protobuf field <code>string uri = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->uri = $var;

        return $this;
    }

    /**
     * For BigQuery inputs defines the columns that should be used for dimensions
     * (including time and group ID).
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.BigqueryMapping bq_mapping = 2;</code>
     * @return \Google\Cloud\Timeseriesinsights\V1\BigqueryMapping|null
     */
    public function getBqMapping()
    {
        return $this->bq_mapping;
    }

    public function hasBqMapping()
    {
        return isset($this->bq_mapping);
    }

    public function clearBqMapping()
    {
        unset($this->bq_mapping);
    }

    /**
     * For BigQuery inputs defines the columns that should be used for dimensions
     * (including time and group ID).
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.BigqueryMapping bq_mapping = 2;</code>
     * @param \Google\Cloud\Timeseriesinsights\V1\BigqueryMapping $var
     * @return $this
     */
    public function setBqMapping($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Timeseriesinsights\V1\BigqueryMapping::class);
        $this->bq_mapping = $var;

        return $this;
    }

}

