<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Request for evaluateSlice.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.EvaluateSliceRequest</code>
 */
class EvaluateSliceRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Required. Loaded DataSet to be queried in the format of
     * "projects/{project}/datasets/{dataset}"
     *
     * Generated from protobuf field <code>string dataset = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     */
    protected $dataset = '';
    /**
     * Required. Dimensions with pinned values that specify the slice for which we will
     * fetch the time series.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.PinnedDimension pinned_dimensions = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private $pinned_dimensions;
    /**
     * Required. This is the point in time that we want to probe for anomalies.
     * See documentation for
     * [QueryDataSetRequest.detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time].
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp detection_time = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    protected $detection_time = null;
    /**
     * Parameters controlling how we will build the time series used to predict
     * the [detectionTime][google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time] value for this slice.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.TimeseriesParams timeseries_params = 4;</code>
     */
    protected $timeseries_params = null;
    /**
     * Parameters that control the time series forecasting models, such as the
     * sensitivity of the anomaly detection.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.ForecastParams forecast_params = 5;</code>
     */
    protected $forecast_params = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $dataset
     *           Required. Loaded DataSet to be queried in the format of
     *           "projects/{project}/datasets/{dataset}"
     *     @type array<\Google\Cloud\Timeseriesinsights\V1\PinnedDimension>|\Google\Protobuf\Internal\RepeatedField $pinned_dimensions
     *           Required. Dimensions with pinned values that specify the slice for which we will
     *           fetch the time series.
     *     @type \Google\Protobuf\Timestamp $detection_time
     *           Required. This is the point in time that we want to probe for anomalies.
     *           See documentation for
     *           [QueryDataSetRequest.detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time].
     *     @type \Google\Cloud\Timeseriesinsights\V1\TimeseriesParams $timeseries_params
     *           Parameters controlling how we will build the time series used to predict
     *           the [detectionTime][google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time] value for this slice.
     *     @type \Google\Cloud\Timeseriesinsights\V1\ForecastParams $forecast_params
     *           Parameters that control the time series forecasting models, such as the
     *           sensitivity of the anomaly detection.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * Required. Loaded DataSet to be queried in the format of
     * "projects/{project}/datasets/{dataset}"
     *
     * Generated from protobuf field <code>string dataset = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @return string
     */
    public function getDataset()
    {
        return $this->dataset;
    }

    /**
     * Required. Loaded DataSet to be queried in the format of
     * "projects/{project}/datasets/{dataset}"
     *
     * Generated from protobuf field <code>string dataset = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = {</code>
     * @param string $var
     * @return $this
     */
    public function setDataset($var)
    {
        GPBUtil::checkString($var, True);
        $this->dataset = $var;

        return $this;
    }

    /**
     * Required. Dimensions with pinned values that specify the slice for which we will
     * fetch the time series.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.PinnedDimension pinned_dimensions = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPinnedDimensions()
    {
        return $this->pinned_dimensions;
    }

    /**
     * Required. Dimensions with pinned values that specify the slice for which we will
     * fetch the time series.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.PinnedDimension pinned_dimensions = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param array<\Google\Cloud\Timeseriesinsights\V1\PinnedDimension>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPinnedDimensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Timeseriesinsights\V1\PinnedDimension::class);
        $this->pinned_dimensions = $arr;

        return $this;
    }

    /**
     * Required. This is the point in time that we want to probe for anomalies.
     * See documentation for
     * [QueryDataSetRequest.detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time].
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp detection_time = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getDetectionTime()
    {
        return $this->detection_time;
    }

    public function hasDetectionTime()
    {
        return isset($this->detection_time);
    }

    public function clearDetectionTime()
    {
        unset($this->detection_time);
    }

    /**
     * Required. This is the point in time that we want to probe for anomalies.
     * See documentation for
     * [QueryDataSetRequest.detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time].
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp detection_time = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDetectionTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->detection_time = $var;

        return $this;
    }

    /**
     * Parameters controlling how we will build the time series used to predict
     * the [detectionTime][google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time] value for this slice.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.TimeseriesParams timeseries_params = 4;</code>
     * @return \Google\Cloud\Timeseriesinsights\V1\TimeseriesParams|null
     */
    public function getTimeseriesParams()
    {
        return $this->timeseries_params;
    }

    public function hasTimeseriesParams()
    {
        return isset($this->timeseries_params);
    }

    public function clearTimeseriesParams()
    {
        unset($this->timeseries_params);
    }

    /**
     * Parameters controlling how we will build the time series used to predict
     * the [detectionTime][google.cloud.timeseriesinsights.v1.EvaluateSliceRequest.detection_time] value for this slice.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.TimeseriesParams timeseries_params = 4;</code>
     * @param \Google\Cloud\Timeseriesinsights\V1\TimeseriesParams $var
     * @return $this
     */
    public function setTimeseriesParams($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Timeseriesinsights\V1\TimeseriesParams::class);
        $this->timeseries_params = $var;

        return $this;
    }

    /**
     * Parameters that control the time series forecasting models, such as the
     * sensitivity of the anomaly detection.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.ForecastParams forecast_params = 5;</code>
     * @return \Google\Cloud\Timeseriesinsights\V1\ForecastParams|null
     */
    public function getForecastParams()
    {
        return $this->forecast_params;
    }

    public function hasForecastParams()
    {
        return isset($this->forecast_params);
    }

    public function clearForecastParams()
    {
        unset($this->forecast_params);
    }

    /**
     * Parameters that control the time series forecasting models, such as the
     * sensitivity of the anomaly detection.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.ForecastParams forecast_params = 5;</code>
     * @param \Google\Cloud\Timeseriesinsights\V1\ForecastParams $var
     * @return $this
     */
    public function setForecastParams($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Timeseriesinsights\V1\ForecastParams::class);
        $this->forecast_params = $var;

        return $this;
    }

}

