<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Forecast result for a given slice.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.EvaluatedSlice</code>
 */
class EvaluatedSlice extends \Google\Protobuf\Internal\Message
{
    /**
     * Values for all categorical dimensions that uniquely identify this slice.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.PinnedDimension dimensions = 1;</code>
     */
    private $dimensions;
    /**
     * The actual value at the detection time (see
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]).
     * **NOTE**: This value can be an estimate, so it should not be used as a
     * source of truth.
     *
     * Generated from protobuf field <code>optional double detection_point_actual = 11;</code>
     */
    protected $detection_point_actual = null;
    /**
     * The expected value at the detection time, which is obtained by forecasting
     * on the historical time series.
     *
     * Generated from protobuf field <code>optional double detection_point_forecast = 12;</code>
     */
    protected $detection_point_forecast = null;
    /**
     * How much our forecast model expects the detection point actual will
     * deviate from its forecasted value based on how well it fit the input time
     * series.
     * In general, we expect the `detectionPointActual` to
     * be in the `[detectionPointForecast - expectedDeviation,
     * detectionPointForecast + expectedDeviation]` range. The more the actual
     * value is outside this range, the more statistically significant the
     * anomaly is.
     * The expected deviation is always positive.
     *
     * Generated from protobuf field <code>optional double expected_deviation = 16;</code>
     */
    protected $expected_deviation = null;
    /**
     * Summarizes how significant the change between the actual and forecasted
     * detection points are compared with the historical patterns observed on the
     * [history][google.cloud.timeseriesinsights.v1.EvaluatedSlice.history] time series.
     * Defined as *|a - f| / (e + nt)*, where:
     * - *a* is the [detectionPointActual][google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_actual].
     * - *f* is the [detectionPointForecast][google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_forecast].
     * - *e* is the [expectedDeviation][google.cloud.timeseriesinsights.v1.EvaluatedSlice.expected_deviation].
     * - *nt` is the [noiseThreshold][google.cloud.timeseriesinsights.v1.ForecastParams.noise_threshold].
     * Anomaly scores between different requests and datasets are comparable. As
     * a guideline, the risk of a slice being an anomaly based on the anomaly
     * score is:
     * - **Very High** if `anomalyScore` > 5.
     * - **High** if the `anomalyScore` is in the [2, 5] range.
     * - **Medium** if the `anomalyScore` is in the [1, 2) range.
     * - **Low** if the `anomalyScore` is < 1.
     * If there were issues evaluating this slice, then the anomaly score will be
     * set to -1.0 and the [status][google.cloud.timeseriesinsights.v1.EvaluatedSlice.status] field will contain details on what
     * went wrong.
     *
     * Generated from protobuf field <code>optional double anomaly_score = 17;</code>
     */
    protected $anomaly_score = null;
    /**
     * The actual values in the `[`
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `-`
     * [forecastHistory][google.cloud.timeseriesinsights.v1.TimeseriesParams.forecast_history]`,`
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `]` time
     * range.
     * **NOTE**: This field is only populated if
     * [returnTimeseries][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries] is true.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.Timeseries history = 5;</code>
     */
    protected $history = null;
    /**
     * The forecasted values in the `[`
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `+`
     * [granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]`,`
     * [forecastParams.horizonTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.forecast_params] `]` time
     * range.
     * **NOTE**: This field is only populated if
     * [returnTimeseries][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries] is true.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.Timeseries forecast = 10;</code>
     */
    protected $forecast = null;
    /**
     * Evaluation status. Contains an error message if the `anomalyScore` is < 0.
     * Possible error messages:
     * - **"Time series too sparse"**: The returned time series for this slice did
     * not contain enough data points (we require a minimum of 10).
     * - **"Not enough recent time series points"**: The time series contains the
     * minimum of 10 points, but there are not enough close in time to the
     * detection point.
     * - **"Missing detection point data"**: There were not events to be
     * aggregated within the `[detectionTime, detectionTime + granularity]` time
     * interval, so we don't have an actual value with which we can compare our
     * prediction.
     * - **"Data retrieval error"**: We failed to retrieve the time series data
     * for this slice and could not evaluate it successfully. Should be a
     * transient error.
     * - **"Internal server error"**: Internal unexpected error.
     *
     * Generated from protobuf field <code>.google.rpc.Status status = 18;</code>
     */
    protected $status = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Google\Cloud\Timeseriesinsights\V1\PinnedDimension>|\Google\Protobuf\Internal\RepeatedField $dimensions
     *           Values for all categorical dimensions that uniquely identify this slice.
     *     @type float $detection_point_actual
     *           The actual value at the detection time (see
     *           [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]).
     *           **NOTE**: This value can be an estimate, so it should not be used as a
     *           source of truth.
     *     @type float $detection_point_forecast
     *           The expected value at the detection time, which is obtained by forecasting
     *           on the historical time series.
     *     @type float $expected_deviation
     *           How much our forecast model expects the detection point actual will
     *           deviate from its forecasted value based on how well it fit the input time
     *           series.
     *           In general, we expect the `detectionPointActual` to
     *           be in the `[detectionPointForecast - expectedDeviation,
     *           detectionPointForecast + expectedDeviation]` range. The more the actual
     *           value is outside this range, the more statistically significant the
     *           anomaly is.
     *           The expected deviation is always positive.
     *     @type float $anomaly_score
     *           Summarizes how significant the change between the actual and forecasted
     *           detection points are compared with the historical patterns observed on the
     *           [history][google.cloud.timeseriesinsights.v1.EvaluatedSlice.history] time series.
     *           Defined as *|a - f| / (e + nt)*, where:
     *           - *a* is the [detectionPointActual][google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_actual].
     *           - *f* is the [detectionPointForecast][google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_forecast].
     *           - *e* is the [expectedDeviation][google.cloud.timeseriesinsights.v1.EvaluatedSlice.expected_deviation].
     *           - *nt` is the [noiseThreshold][google.cloud.timeseriesinsights.v1.ForecastParams.noise_threshold].
     *           Anomaly scores between different requests and datasets are comparable. As
     *           a guideline, the risk of a slice being an anomaly based on the anomaly
     *           score is:
     *           - **Very High** if `anomalyScore` > 5.
     *           - **High** if the `anomalyScore` is in the [2, 5] range.
     *           - **Medium** if the `anomalyScore` is in the [1, 2) range.
     *           - **Low** if the `anomalyScore` is < 1.
     *           If there were issues evaluating this slice, then the anomaly score will be
     *           set to -1.0 and the [status][google.cloud.timeseriesinsights.v1.EvaluatedSlice.status] field will contain details on what
     *           went wrong.
     *     @type \Google\Cloud\Timeseriesinsights\V1\Timeseries $history
     *           The actual values in the `[`
     *           [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `-`
     *           [forecastHistory][google.cloud.timeseriesinsights.v1.TimeseriesParams.forecast_history]`,`
     *           [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `]` time
     *           range.
     *           **NOTE**: This field is only populated if
     *           [returnTimeseries][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries] is true.
     *     @type \Google\Cloud\Timeseriesinsights\V1\Timeseries $forecast
     *           The forecasted values in the `[`
     *           [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `+`
     *           [granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]`,`
     *           [forecastParams.horizonTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.forecast_params] `]` time
     *           range.
     *           **NOTE**: This field is only populated if
     *           [returnTimeseries][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries] is true.
     *     @type \Google\Rpc\Status $status
     *           Evaluation status. Contains an error message if the `anomalyScore` is < 0.
     *           Possible error messages:
     *           - **"Time series too sparse"**: The returned time series for this slice did
     *           not contain enough data points (we require a minimum of 10).
     *           - **"Not enough recent time series points"**: The time series contains the
     *           minimum of 10 points, but there are not enough close in time to the
     *           detection point.
     *           - **"Missing detection point data"**: There were not events to be
     *           aggregated within the `[detectionTime, detectionTime + granularity]` time
     *           interval, so we don't have an actual value with which we can compare our
     *           prediction.
     *           - **"Data retrieval error"**: We failed to retrieve the time series data
     *           for this slice and could not evaluate it successfully. Should be a
     *           transient error.
     *           - **"Internal server error"**: Internal unexpected error.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * Values for all categorical dimensions that uniquely identify this slice.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.PinnedDimension dimensions = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDimensions()
    {
        return $this->dimensions;
    }

    /**
     * Values for all categorical dimensions that uniquely identify this slice.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.PinnedDimension dimensions = 1;</code>
     * @param array<\Google\Cloud\Timeseriesinsights\V1\PinnedDimension>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDimensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Timeseriesinsights\V1\PinnedDimension::class);
        $this->dimensions = $arr;

        return $this;
    }

    /**
     * The actual value at the detection time (see
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]).
     * **NOTE**: This value can be an estimate, so it should not be used as a
     * source of truth.
     *
     * Generated from protobuf field <code>optional double detection_point_actual = 11;</code>
     * @return float
     */
    public function getDetectionPointActual()
    {
        return isset($this->detection_point_actual) ? $this->detection_point_actual : 0.0;
    }

    public function hasDetectionPointActual()
    {
        return isset($this->detection_point_actual);
    }

    public function clearDetectionPointActual()
    {
        unset($this->detection_point_actual);
    }

    /**
     * The actual value at the detection time (see
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time]).
     * **NOTE**: This value can be an estimate, so it should not be used as a
     * source of truth.
     *
     * Generated from protobuf field <code>optional double detection_point_actual = 11;</code>
     * @param float $var
     * @return $this
     */
    public function setDetectionPointActual($var)
    {
        GPBUtil::checkDouble($var);
        $this->detection_point_actual = $var;

        return $this;
    }

    /**
     * The expected value at the detection time, which is obtained by forecasting
     * on the historical time series.
     *
     * Generated from protobuf field <code>optional double detection_point_forecast = 12;</code>
     * @return float
     */
    public function getDetectionPointForecast()
    {
        return isset($this->detection_point_forecast) ? $this->detection_point_forecast : 0.0;
    }

    public function hasDetectionPointForecast()
    {
        return isset($this->detection_point_forecast);
    }

    public function clearDetectionPointForecast()
    {
        unset($this->detection_point_forecast);
    }

    /**
     * The expected value at the detection time, which is obtained by forecasting
     * on the historical time series.
     *
     * Generated from protobuf field <code>optional double detection_point_forecast = 12;</code>
     * @param float $var
     * @return $this
     */
    public function setDetectionPointForecast($var)
    {
        GPBUtil::checkDouble($var);
        $this->detection_point_forecast = $var;

        return $this;
    }

    /**
     * How much our forecast model expects the detection point actual will
     * deviate from its forecasted value based on how well it fit the input time
     * series.
     * In general, we expect the `detectionPointActual` to
     * be in the `[detectionPointForecast - expectedDeviation,
     * detectionPointForecast + expectedDeviation]` range. The more the actual
     * value is outside this range, the more statistically significant the
     * anomaly is.
     * The expected deviation is always positive.
     *
     * Generated from protobuf field <code>optional double expected_deviation = 16;</code>
     * @return float
     */
    public function getExpectedDeviation()
    {
        return isset($this->expected_deviation) ? $this->expected_deviation : 0.0;
    }

    public function hasExpectedDeviation()
    {
        return isset($this->expected_deviation);
    }

    public function clearExpectedDeviation()
    {
        unset($this->expected_deviation);
    }

    /**
     * How much our forecast model expects the detection point actual will
     * deviate from its forecasted value based on how well it fit the input time
     * series.
     * In general, we expect the `detectionPointActual` to
     * be in the `[detectionPointForecast - expectedDeviation,
     * detectionPointForecast + expectedDeviation]` range. The more the actual
     * value is outside this range, the more statistically significant the
     * anomaly is.
     * The expected deviation is always positive.
     *
     * Generated from protobuf field <code>optional double expected_deviation = 16;</code>
     * @param float $var
     * @return $this
     */
    public function setExpectedDeviation($var)
    {
        GPBUtil::checkDouble($var);
        $this->expected_deviation = $var;

        return $this;
    }

    /**
     * Summarizes how significant the change between the actual and forecasted
     * detection points are compared with the historical patterns observed on the
     * [history][google.cloud.timeseriesinsights.v1.EvaluatedSlice.history] time series.
     * Defined as *|a - f| / (e + nt)*, where:
     * - *a* is the [detectionPointActual][google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_actual].
     * - *f* is the [detectionPointForecast][google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_forecast].
     * - *e* is the [expectedDeviation][google.cloud.timeseriesinsights.v1.EvaluatedSlice.expected_deviation].
     * - *nt` is the [noiseThreshold][google.cloud.timeseriesinsights.v1.ForecastParams.noise_threshold].
     * Anomaly scores between different requests and datasets are comparable. As
     * a guideline, the risk of a slice being an anomaly based on the anomaly
     * score is:
     * - **Very High** if `anomalyScore` > 5.
     * - **High** if the `anomalyScore` is in the [2, 5] range.
     * - **Medium** if the `anomalyScore` is in the [1, 2) range.
     * - **Low** if the `anomalyScore` is < 1.
     * If there were issues evaluating this slice, then the anomaly score will be
     * set to -1.0 and the [status][google.cloud.timeseriesinsights.v1.EvaluatedSlice.status] field will contain details on what
     * went wrong.
     *
     * Generated from protobuf field <code>optional double anomaly_score = 17;</code>
     * @return float
     */
    public function getAnomalyScore()
    {
        return isset($this->anomaly_score) ? $this->anomaly_score : 0.0;
    }

    public function hasAnomalyScore()
    {
        return isset($this->anomaly_score);
    }

    public function clearAnomalyScore()
    {
        unset($this->anomaly_score);
    }

    /**
     * Summarizes how significant the change between the actual and forecasted
     * detection points are compared with the historical patterns observed on the
     * [history][google.cloud.timeseriesinsights.v1.EvaluatedSlice.history] time series.
     * Defined as *|a - f| / (e + nt)*, where:
     * - *a* is the [detectionPointActual][google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_actual].
     * - *f* is the [detectionPointForecast][google.cloud.timeseriesinsights.v1.EvaluatedSlice.detection_point_forecast].
     * - *e* is the [expectedDeviation][google.cloud.timeseriesinsights.v1.EvaluatedSlice.expected_deviation].
     * - *nt` is the [noiseThreshold][google.cloud.timeseriesinsights.v1.ForecastParams.noise_threshold].
     * Anomaly scores between different requests and datasets are comparable. As
     * a guideline, the risk of a slice being an anomaly based on the anomaly
     * score is:
     * - **Very High** if `anomalyScore` > 5.
     * - **High** if the `anomalyScore` is in the [2, 5] range.
     * - **Medium** if the `anomalyScore` is in the [1, 2) range.
     * - **Low** if the `anomalyScore` is < 1.
     * If there were issues evaluating this slice, then the anomaly score will be
     * set to -1.0 and the [status][google.cloud.timeseriesinsights.v1.EvaluatedSlice.status] field will contain details on what
     * went wrong.
     *
     * Generated from protobuf field <code>optional double anomaly_score = 17;</code>
     * @param float $var
     * @return $this
     */
    public function setAnomalyScore($var)
    {
        GPBUtil::checkDouble($var);
        $this->anomaly_score = $var;

        return $this;
    }

    /**
     * The actual values in the `[`
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `-`
     * [forecastHistory][google.cloud.timeseriesinsights.v1.TimeseriesParams.forecast_history]`,`
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `]` time
     * range.
     * **NOTE**: This field is only populated if
     * [returnTimeseries][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries] is true.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.Timeseries history = 5;</code>
     * @return \Google\Cloud\Timeseriesinsights\V1\Timeseries|null
     */
    public function getHistory()
    {
        return $this->history;
    }

    public function hasHistory()
    {
        return isset($this->history);
    }

    public function clearHistory()
    {
        unset($this->history);
    }

    /**
     * The actual values in the `[`
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `-`
     * [forecastHistory][google.cloud.timeseriesinsights.v1.TimeseriesParams.forecast_history]`,`
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `]` time
     * range.
     * **NOTE**: This field is only populated if
     * [returnTimeseries][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries] is true.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.Timeseries history = 5;</code>
     * @param \Google\Cloud\Timeseriesinsights\V1\Timeseries $var
     * @return $this
     */
    public function setHistory($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Timeseriesinsights\V1\Timeseries::class);
        $this->history = $var;

        return $this;
    }

    /**
     * The forecasted values in the `[`
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `+`
     * [granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]`,`
     * [forecastParams.horizonTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.forecast_params] `]` time
     * range.
     * **NOTE**: This field is only populated if
     * [returnTimeseries][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries] is true.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.Timeseries forecast = 10;</code>
     * @return \Google\Cloud\Timeseriesinsights\V1\Timeseries|null
     */
    public function getForecast()
    {
        return $this->forecast;
    }

    public function hasForecast()
    {
        return isset($this->forecast);
    }

    public function clearForecast()
    {
        unset($this->forecast);
    }

    /**
     * The forecasted values in the `[`
     * [detectionTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.detection_time] `+`
     * [granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]`,`
     * [forecastParams.horizonTime][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.forecast_params] `]` time
     * range.
     * **NOTE**: This field is only populated if
     * [returnTimeseries][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.return_timeseries] is true.
     *
     * Generated from protobuf field <code>.google.cloud.timeseriesinsights.v1.Timeseries forecast = 10;</code>
     * @param \Google\Cloud\Timeseriesinsights\V1\Timeseries $var
     * @return $this
     */
    public function setForecast($var)
    {
        GPBUtil::checkMessage($var, \Google\Cloud\Timeseriesinsights\V1\Timeseries::class);
        $this->forecast = $var;

        return $this;
    }

    /**
     * Evaluation status. Contains an error message if the `anomalyScore` is < 0.
     * Possible error messages:
     * - **"Time series too sparse"**: The returned time series for this slice did
     * not contain enough data points (we require a minimum of 10).
     * - **"Not enough recent time series points"**: The time series contains the
     * minimum of 10 points, but there are not enough close in time to the
     * detection point.
     * - **"Missing detection point data"**: There were not events to be
     * aggregated within the `[detectionTime, detectionTime + granularity]` time
     * interval, so we don't have an actual value with which we can compare our
     * prediction.
     * - **"Data retrieval error"**: We failed to retrieve the time series data
     * for this slice and could not evaluate it successfully. Should be a
     * transient error.
     * - **"Internal server error"**: Internal unexpected error.
     *
     * Generated from protobuf field <code>.google.rpc.Status status = 18;</code>
     * @return \Google\Rpc\Status|null
     */
    public function getStatus()
    {
        return $this->status;
    }

    public function hasStatus()
    {
        return isset($this->status);
    }

    public function clearStatus()
    {
        unset($this->status);
    }

    /**
     * Evaluation status. Contains an error message if the `anomalyScore` is < 0.
     * Possible error messages:
     * - **"Time series too sparse"**: The returned time series for this slice did
     * not contain enough data points (we require a minimum of 10).
     * - **"Not enough recent time series points"**: The time series contains the
     * minimum of 10 points, but there are not enough close in time to the
     * detection point.
     * - **"Missing detection point data"**: There were not events to be
     * aggregated within the `[detectionTime, detectionTime + granularity]` time
     * interval, so we don't have an actual value with which we can compare our
     * prediction.
     * - **"Data retrieval error"**: We failed to retrieve the time series data
     * for this slice and could not evaluate it successfully. Should be a
     * transient error.
     * - **"Internal server error"**: Internal unexpected error.
     *
     * Generated from protobuf field <code>.google.rpc.Status status = 18;</code>
     * @param \Google\Rpc\Status $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkMessage($var, \Google\Rpc\Status::class);
        $this->status = $var;

        return $this;
    }

}

