<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Represents an entry in a data source.
 * Each Event has:
 * * A timestamp at which the event occurs.
 * * One or multiple dimensions.
 * * Optionally, a group ID that allows clients to group logically related
 *   events (for example, all events representing payments transactions done by
 *   a user in a day have the same group ID).  If a group ID is not provided, an
 *   internal one will be generated based on the content and `eventTime`.
 * **NOTE**:
 * * Internally, we discretize time in equal-sized chunks and we assume an
 *   event has a 0
 *   [TimeseriesPoint.value][google.cloud.timeseriesinsights.v1.TimeseriesPoint.value]
 *   in a chunk that does not contain any occurrences of an event in the input.
 * * The number of Events with the same group ID should be limited.
 * * Group ID *cannot* be queried.
 * * Group ID does *not* correspond to a user ID or the like. If a user ID is of
 *   interest to be queried, use a user ID `dimension` instead.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Event dimensions.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.EventDimension dimensions = 1;</code>
     */
    private $dimensions;
    /**
     * Event group ID.
     * **NOTE**: JSON encoding should use a string to hold a 64-bit integer value,
     * because a native JSON number holds only 53 binary bits for an integer.
     *
     * Generated from protobuf field <code>int64 group_id = 2;</code>
     */
    protected $group_id = 0;
    /**
     * Event timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp event_time = 3;</code>
     */
    protected $event_time = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Google\Cloud\Timeseriesinsights\V1\EventDimension>|\Google\Protobuf\Internal\RepeatedField $dimensions
     *           Event dimensions.
     *     @type int|string $group_id
     *           Event group ID.
     *           **NOTE**: JSON encoding should use a string to hold a 64-bit integer value,
     *           because a native JSON number holds only 53 binary bits for an integer.
     *     @type \Google\Protobuf\Timestamp $event_time
     *           Event timestamp.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * Event dimensions.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.EventDimension dimensions = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDimensions()
    {
        return $this->dimensions;
    }

    /**
     * Event dimensions.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.EventDimension dimensions = 1;</code>
     * @param array<\Google\Cloud\Timeseriesinsights\V1\EventDimension>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDimensions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Timeseriesinsights\V1\EventDimension::class);
        $this->dimensions = $arr;

        return $this;
    }

    /**
     * Event group ID.
     * **NOTE**: JSON encoding should use a string to hold a 64-bit integer value,
     * because a native JSON number holds only 53 binary bits for an integer.
     *
     * Generated from protobuf field <code>int64 group_id = 2;</code>
     * @return int|string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     * Event group ID.
     * **NOTE**: JSON encoding should use a string to hold a 64-bit integer value,
     * because a native JSON number holds only 53 binary bits for an integer.
     *
     * Generated from protobuf field <code>int64 group_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkInt64($var);
        $this->group_id = $var;

        return $this;
    }

    /**
     * Event timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp event_time = 3;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getEventTime()
    {
        return $this->event_time;
    }

    public function hasEventTime()
    {
        return isset($this->event_time);
    }

    public function clearEventTime()
    {
        unset($this->event_time);
    }

    /**
     * Event timestamp.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp event_time = 3;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setEventTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->event_time = $var;

        return $this;
    }

}

