<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Represents an event dimension.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.EventDimension</code>
 */
class EventDimension extends \Google\Protobuf\Internal\Message
{
    /**
     * Dimension name.
     * **NOTE**: `EventDimension` names must be composed of alphanumeric
     * characters only, and are case insensitive. Unicode characters are *not*
     * supported. The underscore '_' is also allowed.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Dimension name.
     *           **NOTE**: `EventDimension` names must be composed of alphanumeric
     *           characters only, and are case insensitive. Unicode characters are *not*
     *           supported. The underscore '_' is also allowed.
     *     @type string $string_val
     *           String representation.
     *           **NOTE**: String values are case insensitive. Unicode characters are
     *           supported.
     *     @type int|string $long_val
     *           Long representation.
     *     @type bool $bool_val
     *           Bool representation.
     *     @type float $double_val
     *           Double representation.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * Dimension name.
     * **NOTE**: `EventDimension` names must be composed of alphanumeric
     * characters only, and are case insensitive. Unicode characters are *not*
     * supported. The underscore '_' is also allowed.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Dimension name.
     * **NOTE**: `EventDimension` names must be composed of alphanumeric
     * characters only, and are case insensitive. Unicode characters are *not*
     * supported. The underscore '_' is also allowed.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * String representation.
     * **NOTE**: String values are case insensitive. Unicode characters are
     * supported.
     *
     * Generated from protobuf field <code>string string_val = 2;</code>
     * @return string
     */
    public function getStringVal()
    {
        return $this->readOneof(2);
    }

    public function hasStringVal()
    {
        return $this->hasOneof(2);
    }

    /**
     * String representation.
     * **NOTE**: String values are case insensitive. Unicode characters are
     * supported.
     *
     * Generated from protobuf field <code>string string_val = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStringVal($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Long representation.
     *
     * Generated from protobuf field <code>int64 long_val = 3;</code>
     * @return int|string
     */
    public function getLongVal()
    {
        return $this->readOneof(3);
    }

    public function hasLongVal()
    {
        return $this->hasOneof(3);
    }

    /**
     * Long representation.
     *
     * Generated from protobuf field <code>int64 long_val = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLongVal($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Bool representation.
     *
     * Generated from protobuf field <code>bool bool_val = 4;</code>
     * @return bool
     */
    public function getBoolVal()
    {
        return $this->readOneof(4);
    }

    public function hasBoolVal()
    {
        return $this->hasOneof(4);
    }

    /**
     * Bool representation.
     *
     * Generated from protobuf field <code>bool bool_val = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolVal($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Double representation.
     *
     * Generated from protobuf field <code>double double_val = 5;</code>
     * @return float
     */
    public function getDoubleVal()
    {
        return $this->readOneof(5);
    }

    public function hasDoubleVal()
    {
        return $this->hasOneof(5);
    }

    /**
     * Double representation.
     *
     * Generated from protobuf field <code>double double_val = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleVal($var)
    {
        GPBUtil::checkDouble($var);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

