<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Timeseriesinsights\V1\ForecastParams\Period instead.
     * @deprecated
     */
    class ForecastParams_Period {}
}
class_exists(ForecastParams\Period::class);
@trigger_error('Google\Cloud\Timeseriesinsights\V1\ForecastParams_Period is deprecated and will be removed in the next major release. Use Google\Cloud\Timeseriesinsights\V1\ForecastParams\Period instead', E_USER_DEPRECATED);

