<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Created DataSets list response.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.ListDataSetsResponse</code>
 */
class ListDataSetsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The list of created DataSets.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.DataSet datasets = 1;</code>
     */
    private $datasets;
    /**
     * Token to receive the next page of results.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     */
    protected $next_page_token = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Google\Cloud\Timeseriesinsights\V1\DataSet>|\Google\Protobuf\Internal\RepeatedField $datasets
     *           The list of created DataSets.
     *     @type string $next_page_token
     *           Token to receive the next page of results.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * The list of created DataSets.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.DataSet datasets = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDatasets()
    {
        return $this->datasets;
    }

    /**
     * The list of created DataSets.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.DataSet datasets = 1;</code>
     * @param array<\Google\Cloud\Timeseriesinsights\V1\DataSet>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDatasets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Timeseriesinsights\V1\DataSet::class);
        $this->datasets = $arr;

        return $this;
    }

    /**
     * Token to receive the next page of results.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @return string
     */
    public function getNextPageToken()
    {
        return $this->next_page_token;
    }

    /**
     * Token to receive the next page of results.
     *
     * Generated from protobuf field <code>string next_page_token = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNextPageToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->next_page_token = $var;

        return $this;
    }

}

