<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A categorical dimension fixed to a certain value.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.PinnedDimension</code>
 */
class PinnedDimension extends \Google\Protobuf\Internal\Message
{
    /**
     * The name of the dimension for which we are fixing its value.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           The name of the dimension for which we are fixing its value.
     *     @type string $string_val
     *           A string value. This can be used for [dimensions][google.cloud.timeseriesinsights.v1.EventDimension], which
     *           have their value field set to [string_val][google.cloud.timeseriesinsights.v1.EventDimension.string_val].
     *     @type bool $bool_val
     *           A bool value. This can be used for [dimensions][google.cloud.timeseriesinsights.v1.EventDimension], which
     *           have their value field set to [bool_val][google.cloud.timeseriesinsights.v1.EventDimension.bool_val].
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * The name of the dimension for which we are fixing its value.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the dimension for which we are fixing its value.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * A string value. This can be used for [dimensions][google.cloud.timeseriesinsights.v1.EventDimension], which
     * have their value field set to [string_val][google.cloud.timeseriesinsights.v1.EventDimension.string_val].
     *
     * Generated from protobuf field <code>string string_val = 2;</code>
     * @return string
     */
    public function getStringVal()
    {
        return $this->readOneof(2);
    }

    public function hasStringVal()
    {
        return $this->hasOneof(2);
    }

    /**
     * A string value. This can be used for [dimensions][google.cloud.timeseriesinsights.v1.EventDimension], which
     * have their value field set to [string_val][google.cloud.timeseriesinsights.v1.EventDimension.string_val].
     *
     * Generated from protobuf field <code>string string_val = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setStringVal($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * A bool value. This can be used for [dimensions][google.cloud.timeseriesinsights.v1.EventDimension], which
     * have their value field set to [bool_val][google.cloud.timeseriesinsights.v1.EventDimension.bool_val].
     *
     * Generated from protobuf field <code>bool bool_val = 3;</code>
     * @return bool
     */
    public function getBoolVal()
    {
        return $this->readOneof(3);
    }

    public function hasBoolVal()
    {
        return $this->hasOneof(3);
    }

    /**
     * A bool value. This can be used for [dimensions][google.cloud.timeseriesinsights.v1.EventDimension], which
     * have their value field set to [bool_val][google.cloud.timeseriesinsights.v1.EventDimension.bool_val].
     *
     * Generated from protobuf field <code>bool bool_val = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolVal($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

