<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Response for a query executed by the system.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.QueryDataSetResponse</code>
 */
class QueryDataSetResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Loaded DataSet that was queried.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Slices sorted in descending order by their
     * [anomalyScore][google.cloud.timeseriesinsights.v1.EvaluatedSlice.anomaly_score].
     * At most [numReturnedSlices][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.num_returned_slices]
     * slices are present in this field.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.EvaluatedSlice slices = 3;</code>
     */
    private $slices;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Loaded DataSet that was queried.
     *     @type array<\Google\Cloud\Timeseriesinsights\V1\EvaluatedSlice>|\Google\Protobuf\Internal\RepeatedField $slices
     *           Slices sorted in descending order by their
     *           [anomalyScore][google.cloud.timeseriesinsights.v1.EvaluatedSlice.anomaly_score].
     *           At most [numReturnedSlices][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.num_returned_slices]
     *           slices are present in this field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * Loaded DataSet that was queried.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Loaded DataSet that was queried.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Slices sorted in descending order by their
     * [anomalyScore][google.cloud.timeseriesinsights.v1.EvaluatedSlice.anomaly_score].
     * At most [numReturnedSlices][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.num_returned_slices]
     * slices are present in this field.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.EvaluatedSlice slices = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSlices()
    {
        return $this->slices;
    }

    /**
     * Slices sorted in descending order by their
     * [anomalyScore][google.cloud.timeseriesinsights.v1.EvaluatedSlice.anomaly_score].
     * At most [numReturnedSlices][google.cloud.timeseriesinsights.v1.QueryDataSetRequest.num_returned_slices]
     * slices are present in this field.
     *
     * Generated from protobuf field <code>repeated .google.cloud.timeseriesinsights.v1.EvaluatedSlice slices = 3;</code>
     * @param array<\Google\Cloud\Timeseriesinsights\V1\EvaluatedSlice>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSlices($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Cloud\Timeseriesinsights\V1\EvaluatedSlice::class);
        $this->slices = $arr;

        return $this;
    }

}

