<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Timeseriesinsights\V1\TimeseriesParams\AggregationMethod instead.
     * @deprecated
     */
    class TimeseriesParams_AggregationMethod {}
}
class_exists(TimeseriesParams\AggregationMethod::class);
@trigger_error('Google\Cloud\Timeseriesinsights\V1\TimeseriesParams_AggregationMethod is deprecated and will be removed in the next major release. Use Google\Cloud\Timeseriesinsights\V1\TimeseriesParams\AggregationMethod instead', E_USER_DEPRECATED);

