<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/timeseriesinsights/v1/timeseries_insights.proto

namespace Google\Cloud\Timeseriesinsights\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * A point in a time series.
 *
 * Generated from protobuf message <code>google.cloud.timeseriesinsights.v1.TimeseriesPoint</code>
 */
class TimeseriesPoint extends \Google\Protobuf\Internal\Message
{
    /**
     * The timestamp of this point.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 1;</code>
     */
    protected $time = null;
    /**
     * The value for this point.
     * It is computed by aggregating all events in the associated slice that are
     * in the `[time, time + granularity]` range (see
     * [granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]) using the specified
     * [metric][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric].
     *
     * Generated from protobuf field <code>optional double value = 2;</code>
     */
    protected $value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Timestamp $time
     *           The timestamp of this point.
     *     @type float $value
     *           The value for this point.
     *           It is computed by aggregating all events in the associated slice that are
     *           in the `[time, time + granularity]` range (see
     *           [granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]) using the specified
     *           [metric][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric].
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Cloud\Timeseriesinsights\V1\TimeseriesInsights::initOnce();
        parent::__construct($data);
    }

    /**
     * The timestamp of this point.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 1;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTime()
    {
        return $this->time;
    }

    public function hasTime()
    {
        return isset($this->time);
    }

    public function clearTime()
    {
        unset($this->time);
    }

    /**
     * The timestamp of this point.
     *
     * Generated from protobuf field <code>.google.protobuf.Timestamp time = 1;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->time = $var;

        return $this;
    }

    /**
     * The value for this point.
     * It is computed by aggregating all events in the associated slice that are
     * in the `[time, time + granularity]` range (see
     * [granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]) using the specified
     * [metric][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric].
     *
     * Generated from protobuf field <code>optional double value = 2;</code>
     * @return float
     */
    public function getValue()
    {
        return isset($this->value) ? $this->value : 0.0;
    }

    public function hasValue()
    {
        return isset($this->value);
    }

    public function clearValue()
    {
        unset($this->value);
    }

    /**
     * The value for this point.
     * It is computed by aggregating all events in the associated slice that are
     * in the `[time, time + granularity]` range (see
     * [granularity][google.cloud.timeseriesinsights.v1.TimeseriesParams.granularity]) using the specified
     * [metric][google.cloud.timeseriesinsights.v1.TimeseriesParams.metric].
     *
     * Generated from protobuf field <code>optional double value = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->value = $var;

        return $this;
    }

}

